apiVersion: apps/v1
kind: Deployment 
metadata:
  name: library-web-app
spec: 
     replicas: 3
     selector:
       matchLabels:
         app: library-app
     template:
       metadata: 
         labels:
            app: library-app
       spec:
        containers:
        - name: library-app
          image: manokac55/library-app:latest
          ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
   name: simple-react-app
spec:
  ports:
    - port: 8080
      targetPort: 3000
  selector:
     app: library-app
  type: LoadBalancer   




